//
//  WalletCompatTests.swift
//  MyelTests
//
//  Created by Thomas Chardin on 9/11/20.
//  Copyright © 2020 Myel. All rights reserved.
//

import XCTest
@testable import Myel

class WalletCompatTests: XCTestCase {

    func testBasicSignature() throws {
        // This is the address we expect the private key to generate
        let expectedAddr = "t13t4qv2lvlwowq67d2txl7auiddhlppca3nw5yxa"
        // First we import a private key generated by lotus
        let skeyRaw: [UInt8] = [214, 215, 227, 130, 13, 195, 83, 111, 80, 128, 147, 4, 168, 20, 228, 232, 146, 1, 101, 76, 234, 17, 89, 153, 35, 12, 6, 63, 146, 209, 164, 87]
    
        // Then we derive an address
        let pkey = try! Secp256k1.PublicKey(privateKey: skeyRaw, ctx: nil)
        let addr = Address.Secp256k1(pubkey: pkey.rawValue)
        let finalAddr = addr.string
        // Result address should match our lotus address
        XCTAssertEqual(expectedAddr, finalAddr)
        
//        var msg = [UInt8](repeating: 0, count: 32)
//        for (i, _) in msg.enumerated() {
//            msg[i] = UInt8(i)
//        }
//        let msgHex = Data(msg).toHex()
//
//        print(msgHex)
//
//        XCTAssertEqual(msgHex, "wrongValue")
    }
}
